//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartNH) DeepCopyInto(out *AzureVMSchedulerStartNH) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartNH.
func (in *AzureVMSchedulerStartNH) DeepCopy() *AzureVMSchedulerStartNH {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartNH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStartNH) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartNHList) DeepCopyInto(out *AzureVMSchedulerStartNHList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVMSchedulerStartNH, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartNHList.
func (in *AzureVMSchedulerStartNHList) DeepCopy() *AzureVMSchedulerStartNHList {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartNHList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStartNHList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartNHSpec) DeepCopyInto(out *AzureVMSchedulerStartNHSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartNHSpec.
func (in *AzureVMSchedulerStartNHSpec) DeepCopy() *AzureVMSchedulerStartNHSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartNHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartNHStatus) DeepCopyInto(out *AzureVMSchedulerStartNHStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartNHStatus.
func (in *AzureVMSchedulerStartNHStatus) DeepCopy() *AzureVMSchedulerStartNHStatus {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartNHStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopNH) DeepCopyInto(out *AzureVMSchedulerStopNH) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopNH.
func (in *AzureVMSchedulerStopNH) DeepCopy() *AzureVMSchedulerStopNH {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopNH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStopNH) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopNHList) DeepCopyInto(out *AzureVMSchedulerStopNHList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVMSchedulerStopNH, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopNHList.
func (in *AzureVMSchedulerStopNHList) DeepCopy() *AzureVMSchedulerStopNHList {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopNHList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStopNHList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopNHSpec) DeepCopyInto(out *AzureVMSchedulerStopNHSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopNHSpec.
func (in *AzureVMSchedulerStopNHSpec) DeepCopy() *AzureVMSchedulerStopNHSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopNHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopNHStatus) DeepCopyInto(out *AzureVMSchedulerStopNHStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopNHStatus.
func (in *AzureVMSchedulerStopNHStatus) DeepCopy() *AzureVMSchedulerStopNHStatus {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopNHStatus)
	in.DeepCopyInto(out)
	return out
}
