# permissions for end users to view awsvmschedulerstartnhs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsvmschedulerstartnh-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator-nh
    app.kubernetes.io/part-of: vm-scheduler-operator-nh
    app.kubernetes.io/managed-by: kustomize
  name: awsvmschedulerstartnh-viewer-role
rules:
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartnhs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartnhs/status
  verbs:
  - get
