# permissions for end users to view gcpvmschedulerstartnhs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gcpvmschedulerstartnh-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator-nh
    app.kubernetes.io/part-of: vm-scheduler-operator-nh
    app.kubernetes.io/managed-by: kustomize
  name: gcpvmschedulerstartnh-viewer-role
rules:
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstartnhs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstartnhs/status
  verbs:
  - get
