apiVersion: azure.xyzcompany.com/v1
kind: AzureVMSchedulerStartNH
metadata:
  labels:
    app.kubernetes.io/name: azurevmschedulerstartnh
    app.kubernetes.io/instance: azurevmschedulerstartnh-sample
    app.kubernetes.io/part-of: vm-scheduler-operator-nh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vm-scheduler-operator-nh
  name: azurevmschedulerstartnh-sample
spec:
  # TODO(user): Add fields here
