//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartNH) DeepCopyInto(out *AWSVMSchedulerStartNH) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartNH.
func (in *AWSVMSchedulerStartNH) DeepCopy() *AWSVMSchedulerStartNH {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartNH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStartNH) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartNHList) DeepCopyInto(out *AWSVMSchedulerStartNHList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSVMSchedulerStartNH, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartNHList.
func (in *AWSVMSchedulerStartNHList) DeepCopy() *AWSVMSchedulerStartNHList {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartNHList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStartNHList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartNHSpec) DeepCopyInto(out *AWSVMSchedulerStartNHSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartNHSpec.
func (in *AWSVMSchedulerStartNHSpec) DeepCopy() *AWSVMSchedulerStartNHSpec {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartNHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartNHStatus) DeepCopyInto(out *AWSVMSchedulerStartNHStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartNHStatus.
func (in *AWSVMSchedulerStartNHStatus) DeepCopy() *AWSVMSchedulerStartNHStatus {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartNHStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopNH) DeepCopyInto(out *AWSVMSchedulerStopNH) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopNH.
func (in *AWSVMSchedulerStopNH) DeepCopy() *AWSVMSchedulerStopNH {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopNH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStopNH) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopNHList) DeepCopyInto(out *AWSVMSchedulerStopNHList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSVMSchedulerStopNH, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopNHList.
func (in *AWSVMSchedulerStopNHList) DeepCopy() *AWSVMSchedulerStopNHList {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopNHList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStopNHList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopNHSpec) DeepCopyInto(out *AWSVMSchedulerStopNHSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopNHSpec.
func (in *AWSVMSchedulerStopNHSpec) DeepCopy() *AWSVMSchedulerStopNHSpec {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopNHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopNHStatus) DeepCopyInto(out *AWSVMSchedulerStopNHStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopNHStatus.
func (in *AWSVMSchedulerStopNHStatus) DeepCopy() *AWSVMSchedulerStopNHStatus {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopNHStatus)
	in.DeepCopyInto(out)
	return out
}
