//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartNH) DeepCopyInto(out *GCPVMSchedulerStartNH) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartNH.
func (in *GCPVMSchedulerStartNH) DeepCopy() *GCPVMSchedulerStartNH {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartNH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStartNH) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartNHList) DeepCopyInto(out *GCPVMSchedulerStartNHList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPVMSchedulerStartNH, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartNHList.
func (in *GCPVMSchedulerStartNHList) DeepCopy() *GCPVMSchedulerStartNHList {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartNHList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStartNHList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartNHSpec) DeepCopyInto(out *GCPVMSchedulerStartNHSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartNHSpec.
func (in *GCPVMSchedulerStartNHSpec) DeepCopy() *GCPVMSchedulerStartNHSpec {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartNHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartNHStatus) DeepCopyInto(out *GCPVMSchedulerStartNHStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartNHStatus.
func (in *GCPVMSchedulerStartNHStatus) DeepCopy() *GCPVMSchedulerStartNHStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartNHStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopNH) DeepCopyInto(out *GCPVMSchedulerStopNH) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopNH.
func (in *GCPVMSchedulerStopNH) DeepCopy() *GCPVMSchedulerStopNH {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopNH)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStopNH) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopNHList) DeepCopyInto(out *GCPVMSchedulerStopNHList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPVMSchedulerStopNH, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopNHList.
func (in *GCPVMSchedulerStopNHList) DeepCopy() *GCPVMSchedulerStopNHList {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopNHList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStopNHList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopNHSpec) DeepCopyInto(out *GCPVMSchedulerStopNHSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopNHSpec.
func (in *GCPVMSchedulerStopNHSpec) DeepCopy() *GCPVMSchedulerStopNHSpec {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopNHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopNHStatus) DeepCopyInto(out *GCPVMSchedulerStopNHStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopNHStatus.
func (in *GCPVMSchedulerStopNHStatus) DeepCopy() *GCPVMSchedulerStopNHStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopNHStatus)
	in.DeepCopyInto(out)
	return out
}
